# Generated by Django 3.0.3 on 2020-02-27 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(default=9999999999, primary_key=True, serialize=False)),
                ('file_name', models.TextField(default='')),
                ('item_type', models.TextField(default='')),
                ('item_shape', models.TextField(default='')),
                ('item_cat', models.TextField(default='')),
                ('item_value', models.IntegerField(default=0)),
                ('x_1', models.IntegerField(default=0)),
                ('y_1', models.IntegerField(default=0)),
                ('x_2', models.IntegerField(default=0)),
                ('y_2', models.IntegerField(default=0)),
                ('frame', models.TextField(default='')),
                ('cropped_frame', models.TextField(default='')),
                ('region', models.TextField(default='')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
