# Generated by Django 3.0.3 on 2020-03-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseloader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageItem',
            fields=[
                ('id', models.IntegerField(default=9999999999, primary_key=True, serialize=False)),
                ('image_name', models.TextField(default='')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='url_image',
            field=models.URLField(default=''),
        ),
    ]
