# Generated by Django 3.0.3 on 2020-03-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseloader', '0002_auto_20200303_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='comments',
            field=models.TextField(default=''),
        ),
    ]
