# Generated by Django 3.0.3 on 2020-03-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseloader', '0003_item_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignShape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_shape', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SignType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_type', models.TextField(default='')),
            ],
        ),
    ]
