# Generated by Django 3.0.3 on 2020-03-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseloader', '0004_signshape_signtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_icon', models.TextField(default='')),
            ],
        ),
    ]
